Add netlify-build-plugin-debugbear
netlify/plugins pull request #135
Opened 2020-09-02 08:56 UTC by mattzeunert

This plugin makes it easy for DebugBear customers to test each deployment and see how it affected page performance and Lighthouse scores.

**Are you adding a plugin or updating one?**

- [x] Adding a plugin
- [ ] Updating a plugin

**Have you completed the following?**

- [x] Read and followed the [plugin author guidelines](https://github.com/netlify/plugins/blob/master/docs/guidelines.md).
- [x] Included all [required fields](https://github.com/netlify/plugins/blob/master/docs/CONTRIBUTING.md#required-fields) in your entry.
- [x] Tested the plugin [locally](https://docs.netlify.com/cli/get-started/#run-builds-locally) and [on Netlify](https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin), using the plugin version stated in your entry.

**Test plan**

Deploy log: https://app.netlify.com/sites/mystifying-kilby-0e6399/deploys/5f4f59471ee5720008aeeded

---

I've considered using `utils.status.show()` to show the test result links, but it seems this still isn't supported on the Netlify website.

2020-09-02 16:55 UTC, ehmicky commented on plugins.json
> +    "description": "Run tests on DebugBear to see how your deployments affect page performance and Lighthouse scores.",
```suggestion
    "description": "Run tests on DebugBear to see how your deployments affect page performance and Lighthouse scores",
```

2020-09-02 16:56 UTC, ehmicky requested changes
Hi @mattzeunert,

Thanks, this is great! :tada: 
I have added few small issues [directly in the repository](https://github.com/DebugBear/netlify-build-plugin-debugbear/issues?q=is%3Aissue+is%3Aopen+author%3Aehmicky+sort%3Aupdated-desc), please let me know what you think!

2020-09-03 11:56 UTC, ehmicky approved these changes
Thank you so much @mattzeunert!

2020-09-03 11:56 UTC, merged

2020-09-03 12:52 UTC, mattzeunert commented
Thanks for the quick review @ehmicky!

Would you be in me writing an article for the Netlify blog on how to set up performance tests?